### ISSUE TITLE
Incorrect Icon for Equipment Battery MK1

### ISSUE THREAD

**Issue by dexgecko** [doomeer/factorio#54]
The current icon links to:
https://wiki.factorio.com/images/Battery.png

It should link to:
https://wiki.factorio.com/images/Battery-equipment.png

**Comment by DeCristoforis** [comment]
Fixed in pull request #55

**Comment by doomeer** [comment]
Thanks for the report, and thanks for the fix! Sorry I did not fix it myself sooner (but at least I was not as late to merge the pull request :P )
